INSERT INTO camps (name) VALUES ('Prokids - Suche/Jurgów - 2-4.01') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('Krynica - 9-11.01') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('Prokids - Suche - 17-18.01') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('Prokids, Suche - 24-25.01') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('Liga MOZN 31.01-1.02 GrapaSki *') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('Sekcja Camp - Piancavallo, Włochy - 30.01-7.02.2026') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('Family Camp - Piancavallo, Włochy 7-14.02.2026') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('ProKids - Suche - 21.02-22.02') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('ProKids, Kluszkowce - 27.02-1.03') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('Prokids, Kluszkowce - 6-8.03') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('Kids Trophy Flachau, Austria - 12-15.03.2026') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('Livigno 2026, Włochy') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('Hero, Suche/Jurgów - 2-4.01') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('Hero, Krynica - 9-11.01') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('Hero - Turnau, Austria - 14-18.01') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('Hero, Suche - 17.01') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('MPP Hero, Szczyrk - 21-23.01 *') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('Hero, Suche - 24-25.01') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('Sekcja Camp 2 - Piancavallo, Włochy 7-14.02.2026') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('Hero, Długa Polana 19-20.02 MOZN') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('Hero, Kluszkowce 27.02-1.03') ON CONFLICT (name) DO NOTHING;
INSERT INTO camps (name) VALUES ('Hero, Kluszkowce 6-8.03') ON CONFLICT (name) DO NOTHING;
